### ISSUE TITLE
I/O Adapter Abstraction

### ISSUE THREAD

**Issue by gaperton** [VoliJS/Type-R#12]
Consider implementing I/O adapter abstraction to simplify and standardize I/O transport implementations.

#### Option A
A proposal is an `IOTransaction` abstract class which constructor must be included as a static member of the Model:

```javascript
type ResourceId = number | string;

type IOCommand = Create | Read | Update | Destroy | List;

interface Create { type : 'create', json : any }
interface Read { type : 'read', id : ResourceId }
interface Update { type : 'update', id : ResourceId, json : any }
interface Destroy { type : 'destroy', id : ResourceId }
interface List { type : 'list', query? : object }

abstract class IOTransaction {
    constructor( public resourceUrl: string, public command: IOCommand) { }
    IOPromise : Promise< any >
    abstract dispose() : void // Must cancel the pending I/O operation with unresolved promise
}
```

The IOPromise must enclose the server's response. It must be rejected in case of I/O error.

There might be just one I/O operation for the Model pending at the time. The caller is responsible for canceling any pending I/O operation with unresolved promise except (maybe) the subsequent read operations. Disposal of the pending transaction must result in promise rejection.

Consider the automatic population of Record's validation fields in case of I/O error.

Provide the default implementation for the local storage.

The usage example might look like this:
```javascript
@define
class RestEndpoint extends Model {
    static IOTransaction = RestIOTransaction;
    static urlRoot = '/api/rest_endpoint';
}
```

#### Option B

Relative API URL paths resolution. IO endpoints traverse an ownerwhip tree upwards to resolve the path elements. That's gonna be huuuge. :)

```javascript
@define
class Comment extends Model {
    static IOEndpoint = RestEndpoint( './comments' );
}
```

And endpoint interface will be like this:

```javascript
type IOEndpoint = ( relativeResourceUrl : string ) => { relativeResourceUrl : string, IOTransaction : IOTransactionConstructor };
```

Path resolution starts from the bottom of an ownership tree.

1. get the local resource path and put it at the url top.
2. Apply local url rewrite rules.
3. Forward to the parent or put '/' if there are no parent.

That's, in fact, is far more sophisticated.

For the model's attributes, the default local resource url must be equal to the model's attribute name and allow attribute-level override.

For collection elements, local url is the model ID.

The default root url for the model/collection in case, if there are no parent, might be passed as an argument to the endpoint. Or, (preferably) it might be the part of the url rewrite rules.

**Comment by gaperton** [comment]
#### Option C

Control nested endpoints with attribute-level metadata annotations.

```javascript
@define class Post extends Model {
    static attributes = {
        ...
        comments : Comment.Collection.has.io( RestEndpoint( './comments' ) )
    }
}
```

An ability to override IO transport in place seems to be conceptually better than option B.
In this case, local endpoint definition works always except the cases when it is manually overridden. Plus, it gives us an opportunity to use different transport for different situations.

#### Option B'

Works as option B, but just override the path.

```javascript
@define class Post extends Model {
    static attributes = {
        ...
        comments : Comment.Collection.has.url( './comments' )
    }
}
```

With B, we might actually support overriding the transport as in option C at the same time.

**Comment by gaperton** [comment]
The tricky part here is that an "IO endpoint" actually affects both the model and its implicitly defined collection.

Need to think about the semantic of that behavior and choose it carefully. That's the plan for the next major release of the Type-R.

**Comment by gaperton** [comment]
Option B' looks so great that it needs to be implemented in any case.

Semantically it is really simple. It just overrides an attribute's local url. `./` is resolved relative to the closest `Model` parent absolute url.

Which leads us to the...

#### Option D

Separate the transport and the url mechanics as in Option A, use Option B' to override URLs locally.

1. Model uses the transport which is defined by the closest store, or the default transport defined in the model if there are no store defined. There _might_ be an ability to override transport for the specific attribute as well using the separate `.has` annotation.
2. Model uses the default root URL, unless it is overridden by the parent's rewrite rules.

The clutter with the separate definitions of the default root and transaction might be easily solved with the base class definition, like "RestModel".

What is nice about the item 1 of this proposal is that it's quite easy to enforce _read-only_ stores, defining the read-only endpoint at the top.

**Comment by gaperton** [comment]
So far, Option D looks like the best one combining easy definition of custom transports and the URL path manipulation flexibility.

**Comment by gaperton** [comment]
Implemented in `f/promise-io` branch. The future is here, the 2.0 release is close.

**Comment by remaininlight** [comment]
Thanks, looking forward to trying this!
