### ISSUE TITLE
Typescript 2.3.3 errors

### ISSUE THREAD

**Issue by Bolik** [VoliJS/Type-R#14]
I tried to compile simple model definition with typescript 2.3.3. It's failed with:

<pre>node_modules/nestedtypes/lib/type-r/collection/index.d.ts(16,22): error TS2420: Class 'Collection' incorrectly implements interface 'CollectionCore'.
  Types of property '_onChildrenChange' are incompatible.
    Type '(record: Record, options?: TransactionOptions | undefined, initiator?: Transactional | undefined)...' is not assignable to type '(child: Transactional, options: TransactionOptions) => void'.
      Types of parameters 'record' and 'child' are incompatible.
        Type 'Transactional' is not assignable to type 'Record'.
          Property '_previousAttributes' is missing in type 'Transactional'.
node_modules/nestedtypes/lib/type-r/record/transaction.d.ts(57,22): error TS2415: Class 'Record' incorrectly extends base class 'Transactional'.
  Types of property 'each' are incompatible.
    Type '(iteratee: (value?: any, key?: string | undefined) => void, context?: any) => void' is not assignable to type '(iteratee: (val: any, key: string | number) => void, context?: any) => any'.
      Types of parameters 'iteratee' and 'iteratee' are incompatible.
        Type '(val: any, key: string | number) => void' is not assignable to type '(value?: any, key?: string | undefined) => void'.
          Types of parameters 'key' and 'key' are incompatible.
            Type 'string | undefined' is not assignable to type 'string | number'.
              Type 'undefined' is not assignable to type 'string | number'.
node_modules/nestedtypes/lib/type-r/record/transaction.d.ts(57,22): error TS2417: Class static side 'typeof Record' incorrectly extends base class static side 'typeof Transactional'.
  Types of property 'define' are incompatible.
    Type '(protoProps: RecordDefinition, staticProps?: any) => typeof Record' is not assignable to type '(spec?: MessengerDefinition | undefined, statics?: {} | undefined) => MixableConstructor<Transact...'.
      Type 'typeof Record' is not assignable to type 'MixableConstructor<Transactional>'.
        Types of property 'prototype' are incompatible.
          Type 'Record' is not assignable to type 'Transactional'.
            Types of property 'each' are incompatible.
              Type '(iteratee: (value?: any, key?: string | undefined) => void, context?: any) => void' is not assignable to type '(iteratee: (val: any, key: string | number) => void, context?: any) => any'.
                Types of parameters 'iteratee' and 'iteratee' are incompatible.
                  Type '(val: any, key: string | number) => void' is not assignable to type '(value?: any, key?: string | undefined) => void'.
                    Types of parameters 'key' and 'key' are incompatible.
                      Type 'string | undefined' is not assignable to type 'string | number'.
                        Type 'undefined' is not assignable to type 'string | number'.
node_modules/nestedtypes/lib/type-r/relations/store.d.ts(2,22): error TS2415: Class 'Store' incorrectly extends base class 'Record'.
  Types of property 'getStore' are incompatible.
    Type '() => Store' is not assignable to type '() => Transactional'.
      Type 'Store' is not assignable to type 'Transactional'.
        Types of property 'each' are incompatible.
          Type '(iteratee: (value?: any, key?: string | undefined) => void, context?: any) => void' is not assignable to type '(iteratee: (val: any, key: string | number) => void, context?: any) => any'.
            Types of parameters 'iteratee' and 'iteratee' are incompatible.
              Type '(val: any, key: string | number) => void' is not assignable to type '(value?: any, key?: string | undefined) => void'.
                Types of parameters 'key' and 'key' are incompatible.
                  Type 'string | undefined' is not assignable to type 'string | number'.
                    Type 'undefined' is not assignable to type 'string | number'.
</pre>

**Comment by gaperton** [comment]
I didn't test it from TypeScript yet. Just Babel.

But I will check it soon.

**Comment by gaperton** [comment]
Could you share your model definition causing such an errors, please?

**Comment by Bolik** [comment]
i cant compile the simple index.ts:

import { define, Record } from 'type-r'

**Comment by Bolik** [comment]
tsconfig.json:

<pre>
{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "outDir": "./build",
        "jsx": "react",
        "moduleResolution": "node",
        "sourceMap": true,
        "declaration": true,
        "experimentalDecorators": true,
        "removeComments": true,
        "allowSyntheticDefaultImports": true,

        "strict": true,
        "noImplicitAny": false,
        "strictNullChecks": true,
        "noImplicitThis": true,
        "alwaysStrict": true,

        "baseUrl": "./src",
        "paths": {
            "libs": ["libs"],
            "components": ["components"],
            "etc": ["etc"]
        }
    },
    "filesGlob": [
        "src/**/*.ts",
        "src/**/*.tsx"
    ],
    "exclude": [
        "webpack.config.js",
        "postcss.config.js",
        "build",
        "node_modules"
    ],
    "compileOnSave": true
}

</pre>

**Comment by Bolik** [comment]
Today i installed latest type-r from this repo. Previous errors are dissapeared, but there some new:

<pre>
node_modules/type-r/lib/collection/index.d.ts(17,22): error TS2420: Class 'Collection' incorrectly implements interface 'CollectionCore'.
  Types of property '_onChildrenChange' are incompatible.
    Type '(record: Record, options?: TransactionOptions | undefined, initiator?: Transactional | undefined)...' is not assignable to type '(child: Transactional, options: TransactionOptions) => void'.
      Types of parameters 'record' and 'child' are incompatible.
        Type 'Transactional' is not assignable to type 'Record'.
          Property '_previousAttributes' is missing in type 'Transactional'.
node_modules/type-r/lib/record/transaction.d.ts(57,22): error TS2415: Class 'Record' incorrectly extends base class 'Transactional'.
  Types of property 'each' are incompatible.
    Type '(iteratee: (value?: any, key?: string | undefined) => void, context?: any) => void' is not assignable to type '(iteratee: (val: any, key: string | number) => void, context?: any) => any'.
      Types of parameters 'iteratee' and 'iteratee' are incompatible.
        Type '(val: any, key: string | number) => void' is not assignable to type '(value?: any, key?: string | undefined) => void'.
          Types of parameters 'key' and 'key' are incompatible.
            Type 'string | undefined' is not assignable to type 'string | number'.
              Type 'undefined' is not assignable to type 'string | number'.
node_modules/type-r/lib/record/transaction.d.ts(57,22): error TS2417: Class static side 'typeof Record' incorrectly extends base class static side 'typeof Transactional'.
  Types of property 'define' are incompatible.
    Type '(protoProps: RecordDefinition, staticProps?: any) => typeof Record' is not assignable to type '(spec?: MessengerDefinition | undefined, statics?: {} | undefined) => MixableConstructor<Transact...'.
      Type 'typeof Record' is not assignable to type 'MixableConstructor<Transactional>'.
        Types of property 'prototype' are incompatible.
          Type 'Record' is not assignable to type 'Transactional'.
            Types of property 'each' are incompatible.
              Type '(iteratee: (value?: any, key?: string | undefined) => void, context?: any) => void' is not assignable to type '(iteratee: (val: any, key: string | number) => void, context?: any) => any'.
                Types of parameters 'iteratee' and 'iteratee' are incompatible.
                  Type '(val: any, key: string | number) => void' is not assignable to type '(value?: any, key?: string | undefined) => void'.
                    Types of parameters 'key' and 'key' are incompatible.
                      Type 'string | undefined' is not assignable to type 'string | number'.
                        Type 'undefined' is not assignable to type 'string | number'.
node_modules/type-r/lib/relations/store.d.ts(2,22): error TS2415: Class 'Store' incorrectly extends base class 'Record'.
  Types of property 'getStore' are incompatible.
    Type '() => Store' is not assignable to type '() => Transactional'.
      Type 'Store' is not assignable to type 'Transactional'.
        Types of property 'each' are incompatible.
          Type '(iteratee: (value?: any, key?: string | undefined) => void, context?: any) => void' is not assignable to type '(iteratee: (val: any, key: string | number) => void, context?: any) => any'.
            Types of parameters 'iteratee' and 'iteratee' are incompatible.
              Type '(val: any, key: string | number) => void' is not assignable to type '(value?: any, key?: string | undefined) => void'.
                Types of parameters 'key' and 'key' are incompatible.
                  Type 'string | undefined' is not assignable to type 'string | number'.
                    Type 'undefined' is not assignable to type 'string | number'.
</pre>

**Comment by Bolik** [comment]
Another issue:

<pre>
import { define, Record, ChainableAttributeSpec } from 'type-r'

@define export
    class Refbook extends Record {
    static attributes = {
        title: String.has.toJSON(false)
    }
}

export const availableGenders = new Refbook.Collection([
    { id: 'male', title: 'Male' },
    { id: 'female', title: 'Female' }
]);
</pre>

produce on new Refbook.Collection

error TS2511: Cannot create an instance of the abstract class 'Transactional'.

**Comment by gaperton** [comment]
Interesting. That's pretty serious. It strange that tests don't fail.

**Comment by gaperton** [comment]
I'm in the process of adding TypeScript unit tests. Will take a look at this stuff soon.

**Comment by Bolik** [comment]
another issue with Collection

<pre>

@define class OrganizationList extends Record.Collection {
    public load() {}
}

@define export
    class Organization extends Record {
    static Collection = OrganizationList
    static attributes = {
        name: String
    }
}

</pre>

<pre>
src/scenes/auth/scenes/register/data/register.ts(7,2): error TS2345: Argument of type 'typeof OrganizationList' is not assignable to parameter of type 'MixableConstructor<any>'.
  Types of property 'predefine' are incompatible.
    Type '() => typeof Messenger' is not assignable to type '() => MixableConstructor<any>'.
      Type 'typeof Messenger' is not assignable to type 'MixableConstructor<any>'.
        Types of property 'define' are incompatible.
          Type '(protoProps?: MessengerDefinition | undefined, staticProps?: any) => typeof Messenger' is not assignable to type '(definition: ClassDefinition, staticProps?: {} | undefined) => MixableConstructor<any>'.
            Type 'typeof Messenger' is not assignable to type 'MixableConstructor<any>'.
src/scenes/auth/scenes/register/data/register.ts(7,15): error TS2515: Non-abstract class 'OrganizationList' does not implement inherited abstract member '_createTransaction' from class 'Transactional'.
src/scenes/auth/scenes/register/data/register.ts(7,15): error TS2515: Non-abstract class 'OrganizationList' does not implement inherited abstract member '_log' from class 'Transactional'.
src/scenes/auth/scenes/register/data/register.ts(7,15): error TS2515: Non-abstract class 'OrganizationList' does not implement inherited abstract member '_validateNested' from class 'Transactional'.
src/scenes/auth/scenes/register/data/register.ts(7,15): error TS2515: Non-abstract class 'OrganizationList' does not implement inherited abstract member 'clone' from class 'Transactional'.
src/scenes/auth/scenes/register/data/register.ts(7,15): error TS2515: Non-abstract class 'OrganizationList' does not implement inherited abstract member 'each' from class 'Transactional'.
src/scenes/auth/scenes/register/data/register.ts(7,15): error TS2515: Non-abstract class 'OrganizationList' does not implement inherited abstract member 'get' from class 'Transactional'.
src/scenes/auth/scenes/register/data/register.ts(7,15): error TS2515: Non-abstract class 'OrganizationList' does not implement inherited abstract member 'toJSON' from class 'Transactional'.
src/scenes/auth/scenes/register/data/register.ts(12,22): error TS2339: Property 'add' does not exist on type 'OrganizationList'.
src/scenes/auth/scenes/register/data/register.ts(24,5): error TS4028: Public static property 'Collection' of exported class has or is using private name 'OrganizationList'.
</pre>

**Comment by gaperton** [comment]
Will make sure that this stuff will be fixed in the week. Already have TS tests.

**Comment by Bolik** [comment]
Hi,

any news about progress are highly appreciated :)

**Comment by Bolik** [comment]
Hi,

can you commit your typescript changes?

**Comment by gaperton** [comment]
Commited. Should be fine.

**Comment by trusktr** [comment]
Regarding the "has or is using private name" error, I've opened a request to fix issues like these in TypeScript by bringing declaration files to parity with language features. https://github.com/microsoft/TypeScript/issues/35822
