### ISSUE TITLE
How does class definition look in ES6

### ISSUE THREAD

**Issue by far-blue** [VoliJS/Type-R#20]
I'm not aware the @define decorator syntax is supported in ES6 so could you give an example of how you would define a subclass of Record if you are using ES6 style Javascript instead of TypeScript?

**Comment by gaperton** [comment]
Decorators are required to use ES6 classes. Here's what you should do: https://github.com/Volicon/React-MVx/tree/develop/examples/babel-boilerplate

Old Backbone-style classes still work. Just written inside without `static`.

```
Record.extend({
    attributes : { ... }
});
```

**Comment by gaperton** [comment]
https://volicon.github.io/Type-R/#definitions-in-typescript
