### ISSUE TITLE
Collection with comparator - Typescript error

### ISSUE THREAD

**Issue by Bolik** [VoliJS/Type-R#50]
test.ts

<pre>
import { Record, define, Collection } from 'type-r'

@define export
class TestCollection extends Collection {
	static comparator = x => x.mtime
}

@define export
class M extends Record {
	static Collection = TestCollection as any
	static attributes = {
		mtime: Date
	}
}
</pre>

tsc -w

<pre>
test.ts(3,1): error TS1238: Unable to resolve signature of class decorator when called as an expression.
  Type 'ClassDecorator' is not assignable to type 'typeof TestCollection'.
    Property 'comparator' is missing in type 'ClassDecorator'.
</pre>

typescript version 2.6.2

**Comment by gaperton** [comment]
Added the test. https://github.com/Volicon/Type-R/blob/develop/tests/reported-bugs.test.ts#L74

TypeScript version 3.1.  Test passes.

FYI, the PR with the failing test is a bulletproof PR. ;) 99% probability some actions will be taken.

**Comment by gaperton** [comment]
Reopen if it's still an issue and give me an idea how to fix it, please.
